apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-paper
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraftservertest
  template:
    metadata:
      labels:
        app: minecraftservertest
    spec:
      containers:
        - name: minecraftservertest
          image: alpine:latest
          command: ["/bin/sh"]
          args: ["-c", "apk add openjdk17 && cd minecraftsrv && ./sessioncheck.sh"]
          ports:
          - containerPort: 25565
            name: minecraft
            protocol: TCP
          volumeMounts:
            - mountPath: /minecraftsrv
              name: minecraft-data
      volumes:
        - name: minecraft-data
          hostPath:
            path: /home/<youruser>/mcserve
---
apiVersion: v1
kind: Service
metadata:
  name: mc-nodeport
  namespace: minecraft
spec:
  type: NodePort
  selector:
    app: minecraftservertest
  ports:
    - name: minecraft
      port: 25565
      nodePort: 30001
